In [4]:
import numpy as np

In [29]:
print(matrix1 + matrix2)

[[0 0 0]
 [0 0 0]]


In [30]:
print(matrix + 2)

[[3 4 5]
 [6 7 8]]


In [31]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [32]:
matrix2 = np.array([[-1, -2, -3], [-4, -5, -6]])
print(matrix2)

[[-1 -2 -3]
 [-4 -5 -6]]


In [34]:
np.matmul(matrix1, matrix2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)